### ISSUE TITLE
asdf install reports a broken link for all teleport-community versions

### ISSUE THREAD

**Issue by m-ammar** [MaloPolese/asdf-teleport-community#4]
**Describe the bug**

On running `asdf install teleport-community 7.3.26`, I get a 404 error for the curl. 

**Steps to reproduce**

Execute the below commands:
`asdf plugin add teleport-community`
`asdf install teleport-community 7.3.26`

**Expected behavior**

teleport-community edition version 7.3.26 should be installed.

**Screenshots**

![asdf_error](https://user-images.githubusercontent.com/34128636/211602668-f56cd82a-8459-4910-bac4-e21c471e0843.jpg)

**Additional context**

System Info:
Darwin 22.2.0 Darwin Kernel Version 22.2.0: ; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

**Comment by MaloPolese** [comment]
Thank you for this issue. 

At the moment,  Darwin ARM is not supported. However, if you are using MacOS, you can use the package manager brew, to download Teleport for ARM. 

I will do my best to add support for Darwin ARM in the future, or you can do a PR if you want.
